### ISSUE TITLE
Set up a static file server

### ISSUE THREAD

**Issue by jhs** [jeffmjack/template-bootstrap#2]
I strongly recommend this. Tons of stuff doesn't work right when you run from file:/// URLs.

I suggest you set up a Hapi server with a simple directory handler (serve static files from a directory), plus maybe integrate the "Good" plugin which will give you logging.

This makes your project an official Node project, too, so in your package.json you can put you "hapi" dependency. If you name your server file `server.js` then npm will automatically run it for you if you type `npm start`

**Comment by jeffmjack** [comment]
Good call. I'll work on it today.

I'm starting to think more and more that I need to just buckle down and learn gulp instead of trying to reconfigure grunt in all these crazy ways.

Grunt actually reads the project directory's package.json file for stuff.

So that would mean to make bower_components read-only, I'd need to be maintaining an independent package.json, which kind of defeats the purpose of being able to run `bower update`.

**Comment by jhs** [comment]
Why Hapi?

Short answer: I like it way better. As an API to use, it's a lot more explicit. You're handling requests, and sending out responses. I feel like with Express it's all this behind-the-scenes magic based on what plugins you've installed, and in what order.

Hapi is definitely more respected by the high-end (more experienced) of the Node.js community. So it kind of has the Couch vs. Mongo thing. Most people use Mongo. Most experienced people use Couch (or at least anything but Mongo). They make some pretty persuasive arguments about why Express is easy to get started but causes problems as your site gains features and complexity.

Hapi runs walmart.com and to a large extent, it is maintained by Walmart (although it's a community thing now).

Although yes it's true, every example and their dog uses Express, so if you want to go Express for the sake of cutting with the grain, go for it. I was able to do this isomorphic site with Hapi even though all the examples are Express, but yeah that is extra cognitive load.

To be cynical, if this project is for you to do lots of one-off jobs for people, and to test out your own ideas, then you have no long-term maintenance, no deadline to repay your technical debt, so that argument of Hapy falls away. Your customers are left holding the bag. (You could easily argue that that is false because Express experts are 10x more easy to find than Hapi ones.)

Frankly, another alternative actually, would just be to use the http api yourself. It's not that hard to serve static files. Then you have no dependencies to worry about or maintain.

**Comment by jeffmjack** [comment]
Cool, thanks for the explanation.

Yeah, maybe it will also be better for me to be using hapi as well; less dubious contributions to forums that I'll be reading.

**Comment by jeffmjack** [comment]
Still need to update html links to have serve non-broken html, but the server works. I'm leaving it on branch hapi until I have time to sit down and fix all the headers in the HTML files since we'll be serving only stuff in public/, and that's not how the HTML files are written right now - some of them link like this: "../bower_components/jquery[...]".

Do you have any advice on being able to edit just a header file for that sort of thing, like what I could be able to do with rocking the php include thing in html files, then just editing the header.php file?  Right now I'm going through each html file to replace script and link sources and it's annoying.

**Comment by jhs** [comment]
That common header file (and common footers is another frequent requirement): I would think that is the point of Grunt. It is supposed to compile all your work into this one, presentable bundle that browsers can consume.

I would imagine there is some kind of grunt-include, or grunt-concat, or some task that can do these things.  Failing that, you are basically talking about templating, so Grunt will run your templates for you. See if there is a Grunt Mustache task out there, or Grunt Handlebars or something.

**Comment by jhs** [comment]
This is the sort of reason I like Hapi

https://github.com/hueniverse/iron

That is a great example of leaving security nuts-and-bolts to the pros. That package is the solution to lots of super common security errors people make, and it's part of the Hapi family. (It is used by Yar, the session plugin for Hapi.)

**Comment by jeffmjack** [comment]
Surely something similar exists in other ecosystems like express?

Is it just easier to find the right solution in hapi because there's more bullshit floating around in the more widely-used tools?
